# Generated by Django 3.2.9 on 2022-10-16 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
